# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432" # host:container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=example
    volumes:
      - ./postgres/sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql